run:
  timeout: 10m
linters:
  enable:
    - megacheck
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - bodyclose
    - rowserrcheck
    - asciicheck
    - misspell
    - prealloc
    - exportloopref
    - promlinter
    - unconvert
    - dupl
    - goconst
    - unused
  disable:
    - gosec
    - lll
