name: Build all Architectures

on:
  push:
    paths-ignore:
      - '.idea/..'
      - 'docs/**'

  pull_request:
    paths-ignore:
      - '.idea/..'
      - 'docs/**'

jobs:
  # build-x86:
  #   name: Build for x86
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Go
  #     uses: actions/setup-go@v2
  #     with:
  #       go-version: 1.17
  #   - uses: actions/cache@v2
  #     with:
  #       path: |
  #         ~/.cache/go-build
  #         ~/go/pkg/mod
  #       key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
  #       restore-keys: |
  #         ${{ runner.os }}-go-
  #   - name: Run build script
  #     run: ./scripts/build.sh -a amd64,386
  build-arm:
    name: Build for arm
    runs-on: ubuntu-latest
    steps:
    - run: |
        docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: docker://multiarch/ubuntu-core:arm64-bionic
      with:
        args: >
          bash -c
          "apt update &&
          apt install wget gcc file --yes &&
          ./scripts/build.sh -a arm appimagetool"